### ISSUE TITLE
Fix exporting on Android 6.0 (handle new permissions)

### ISSUE THREAD

**Issue by Honeybunch** [Antox/Antox#199]
I made a profile with Antox from F-Droid and tried to export the profile to use with QTox. Hit the export button, crash. I logged out and tried to import. Hit the button and it crashed. Reinstalled, same behaviour. Downloaded from Play store, same behaviour.

I'm on a Nexus 6 running Android 6.0 unrooted with stock rom.

No file / directory picker came up, it just crashed. Anyone else getting this behaviour?

**Comment by agilob** [comment]
Works fine on android 5.1

**Comment by Honeybunch** [comment]
In android 6.0 I guess antox doesn't know how to request permissions. Went into the settings and gave permissions to the app and it worked.

**Comment by subliun** [comment]
Nah. This is an issue. You shouldn't have to go into the settings, Antox should work with 6.0.

**Comment by svalo** [comment]
I had the same issue: I was trying to import a profile I previously backed up from antox back into antox and, as I pressed the import button, Antox crashed. Giving in app setting the permission to read storage fixed.
This is from logcat, maybe it hepls.
I'm using CyanogenMod 13 Nightly on a nexus5, latest antox from f-droid

```
12-22 09:19:59.517   827 17196 I ActivityManager: START u0 {flg=0x14008000 cmp=chat.tox.antox/.activities.CreateAccountActivity} from uid 10093 on display 0
12-22 09:19:59.532   827 14730 W ActivityManager: Duplicate finish request for ActivityRecord{b0675f4 u0 chat.tox.antox/.activities.LoginActivity t282 f}
12-22 09:19:59.573 17765 17790 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-22 09:19:59.586   827   871 I WindowManager: Screen frozen for +472ms due to Window{eb6b4be u0 com.android.systemui.ImageWallpaper}
12-22 09:19:59.610 17765 17790 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 09/02/15, 76f806e, Ibddc658e36
12-22 09:19:59.612 17765 17790 I OpenGLRenderer: Initialized EGL, version 1.4
12-22 09:19:59.665   827   871 I ActivityManager: Displayed chat.tox.antox/.activities.CreateAccountActivity: +130ms (total +593ms)
12-22 09:20:01.592   827   871 I art     : Starting a blocking GC Explicit
12-22 09:20:01.651   827   871 I art     : Explicit concurrent mark sweep GC freed 48044(2MB) AllocSpace objects, 10(384KB) LOS objects, 33% free, 29MB/44MB, paused 1.010ms total 58.952ms
12-22 09:20:01.750 17765 17765 D AndroidRuntime: Shutting down VM
12-22 09:20:01.752 17765 17765 E AndroidRuntime: FATAL EXCEPTION: main
12-22 09:20:01.752 17765 17765 E AndroidRuntime: Process: chat.tox.antox, PID: 17765
12-22 09:20:01.752 17765 17765 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at android.view.View$DeclaredOnClickListener.onClick(View.java:4458)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at android.view.View.performClick(View.java:5204)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:21156)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5466)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-22 09:20:01.752 17765 17765 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at android.view.View$DeclaredOnClickListener.onClick(View.java:4453)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        ... 9 more
12-22 09:20:01.752 17765 17765 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at scala.collection.SeqLike$class.sorted(SeqLike.scala:637)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at scala.collection.mutable.ArrayOps$ofRef.sorted(ArrayOps.scala:186)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at chat.tox.antox.transfer.FileDialog.chat$tox$antox$transfer$FileDialog$$loadFileList(FileDialog.scala:135)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at chat.tox.antox.transfer.FileDialog.<init>(FileDialog.scala:56)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        at chat.tox.antox.activities.CreateAccountActivity.onClickImportProfile(CreateAccountActivity.scala:301)
12-22 09:20:01.752 17765 17765 E AndroidRuntime:        ... 11 more
12-22 09:20:01.754   827  1711 W ActivityManager:   Force finishing activity chat.tox.antox/.activities.CreateAccountActivity
12-22 09:20:01.864   827  1161 I OpenGLRenderer: Initialized EGL, version 1.4
12-22 09:20:02.316   827   866 W ActivityManager: Activity pause timeout for ActivityRecord{9583b5 u0 chat.tox.antox/.activities.CreateAccountActivity t282 f}
12-22 09:20:02.920  2180  2401 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
12-22 09:20:06.470 17765 17765 I Process : Sending signal. PID: 17765 SIG: 9
12-22 09:20:06.525   827 31029 D GraphicsStats: Buffer count: 17
12-22 09:20:06.525   827 31029 I WindowState: WIN DEATH: Window{1daba97 u0 chat.tox.antox/chat.tox.antox.activities.CreateAccountActivity}
12-22 09:20:06.570   827  1650 I ActivityManager: Process chat.tox.antox (pid 17765) has died
```

**Comment by bodtx** [comment]
I have a pull request for this
#260

**Comment by wiiaam** [comment]
Permissions now working
