### ISSUE TITLE
Can't register or sign in

### ISSUE THREAD

**Issue by Pulsar87** [Antox/Antox#258]
i'm working on asus k016 with x86 
android 5.0

every time i try to write a name and press 'register' or 'incognito'
or even when i import my account 

the time i press ok , the app shtusdown and gives me "Unfortunately, Antox has stopped working"

please fix this

**Comment by wiiaam** [comment]
Currently there is no support for x86 devices

**Comment by subliun** [comment]
@wiiaam What did you do

**Comment by wiiaam** [comment]
@subliun its a problem with the libraries afaik

**Comment by wiiaam** [comment]
Ok, seems to be an issue with the file dialogs. @Pulsar87 can you check if it is fixed in update 0.23.339 (should be out on fdroid and play store soon)

**Comment by SnoopySnoopy** [comment]
Hello.

I can't register any profile.
whatever I press "register", "register incognito" or "profile import" causes Antox to crash.

I have the message "Antox" s'est arrêté, that must be the French version for "Unfortunately, Antox has stopped working"

I'm using a fresh install of Antox 0.23.340 (in french) on an Asus zenfone 2 smart phone under  Android 5.0.


his message is supposed to be typed in english, but by a french human :-)

Regards

**Comment by wiiaam** [comment]
@SnoopySnoopy This crash is due to there not being an x86-64 jni library yet. I will set one up soon and include it in the next update, which *should* fix this

```
Caused by: java.util.NoSuchElementException: key not found: x86_64
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$.<init>(ToxLoadJniLibrary.scala:53)
	at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$.<clinit>(ToxLoadJniLibrary.scala)
	... 19 more
```

**Comment by Tmin10** [comment]
I have this bug too on my x86 ZenFone 2.

![screenshot_2016-05-18-22-39-26](https://cloud.githubusercontent.com/assets/1534088/15390883/5b876c0e-1dcf-11e6-846d-2c4a555e25d9.png)
![screenshot_2016-05-18-22-39-45](https://cloud.githubusercontent.com/assets/1534088/15390893/63db33c2-1dcf-11e6-92c7-67f95ca80087.png)
![screenshot_2016-05-18-22-39-54](https://cloud.githubusercontent.com/assets/1534088/15390898/695f22f4-1dcf-11e6-9401-2cf745d1c715.png)
![screenshot_2016-05-18-22-39-59](https://cloud.githubusercontent.com/assets/1534088/15390903/6e221c38-1dcf-11e6-9a78-eaf7758716d1.png)

**Comment by ALPhaKiLLer** [comment]
Same issue here for the ZenFone 2.

Picture of the top of the Stack Trace.
https://i.imgsafe.org/928e2b5f64.png

**Comment by cargy** [comment]
Not on x86_64 platform, but stacktrace looks similar and happens when trying to singup/login or import profile.

I'm getting the following on Samsung Galaxy A3 (2016) SM-A310F 6.0.1 

 FATAL EXCEPTION: main
 Process: chat.tox.antox, PID: 15506
 java.lang.ExceptionInInitializerError
        at im.tox.tox4j.impl.jni.ToxLoadJniLibrary.load(ToxLoadJniLibrary.scala)
        at im.tox.tox4j.impl.jni.ToxCryptoJni.<clinit>(ToxCryptoJni.java:7)
        at im.tox.tox4j.impl.jni.ToxCryptoImpl$.isDataEncrypted(ToxCryptoImpl.scala:25)
        at chat.tox.antox.tox.ToxDataFile$.isEncrypted(ToxDataFile.scala:15)
        at chat.tox.antox.tox.ToxDataFile$.isEncrypted(ToxDataFile.scala:37)
        at chat.tox.antox.tox.ToxDataFile.isEncrypted(ToxDataFile.scala:48)
        at chat.tox.antox.activities.CreateAccountActivity.onImportFileSelected(CreateAccountActivity.scala:378)
        at chat.tox.antox.activities.CreateAccountActivity$$anon$5.fileSelected(CreateAccountActivity.scala:351)
        at chat.tox.antox.transfer.FileDialog$$anon$3.fireEvent(FileDialog.scala:104)
        at chat.tox.antox.transfer.FileDialog$$anon$3.fireEvent(FileDialog.scala:101)
        at chat.tox.antox.transfer.ListenerList$$anonfun$fireEvent$1.apply(FileDialog.scala:211)
        at chat.tox.antox.transfer.ListenerList$$anonfun$fireEvent$1.apply(FileDialog.scala:210)
        at scala.collection.Iterator$class.foreach(Iterator.scala:742)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
...
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.util.NoSuchElementException: key not found: armv8l
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$.<init>(ToxLoadJniLibrary.scala:53)
        at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$.<clinit>(ToxLoadJniLibrary.scala)
        ... 31 more

**Comment by zoff99** [comment]
@wiiaam there must be a different problem. somehow the code tries to load a specific jni library.
thats wrong. android normally does it ok.

i have this version of the error now:
java.util.NoSuchElementException: key not found: armv8l
but it should just load the normal arm

**Comment by zoff99** [comment]
https://github.com/TokTok/jvm-toxcore-c/blob/pr8/src/main/java/im/tox/tox4j/impl/jni/ToxLoadJniLibrary.scala

**Comment by SnoopySnoopy** [comment]
Good new.
This crash at login is no more here since the last update 
0.25. 490 (15490)
thanks
