### ISSUE TITLE
Video call crashes Antox 0.24.383 between Android 4.4.2 

### ISSUE THREAD

**Issue by rdarioc** [Antox/Antox#304]
Here the error level messages from aLogcat:

* * *
E/AndroidRuntime(28150): Process: chat.tox.antox, PID: 28150
E/AndroidRuntime(28150): at chat.tox.antox.ScriptC_yuvToRgb.<init>(ScriptC_yuvToRgb.java:34)
E/AndroidRuntime(28150): at chat.tox.antox.av.Renderer.createScript(VideoDisplay.scala:145)
E/AndroidRuntime(28150): at chat.tox.antox.av.Renderer.recreate(VideoDisplay.scala:133)
E/AndroidRuntime(28150): at chat.tox.antox.av.Renderer.renderVideoFrame(VideoDisplay.scala:187)
E/AndroidRuntime(28150): at chat.tox.antox.av.Renderer$$anonfun$run$1.apply(VideoDisplay.scala:112)
E/AndroidRuntime(28150): at chat.tox.antox.av.Renderer$$anonfun$run$1.apply(VideoDisplay.scala:104)
E/AndroidRuntime(28150): at chat.tox.antox.av.Renderer.run(VideoDisplay.scala:104)
E/AndroidRuntime(28688): Process: chat.tox.antox, PID: 28688
E/AndroidRuntime(28688): at chat.tox.antox.data.State$.logout(State.scala:82)
E/AndroidRuntime(28688): at chat.tox.antox.fragments.MainDrawerFragment.chat$tox$antox$fragments$MainDrawerFragment$$selectItem(MainDrawerFragment.scala:163)
E/AndroidRuntime(28688): at chat.tox.antox.fragments.MainDrawerFragment$$anon$1.onNavigationItemSelected(MainDrawerFragment.scala:51)
* * *

Please let me know if and how I can be of any further support on this matter

**Comment by ars3niy** [comment]
I've just had exactly this problem. The exception is NoSuchMethodException: no such method ScriptC.<init>. I got it working for me by changing targetSdkVersion and renderscriptTargetApi in app/build.gradle from 23 to 17.

I chose 17 because I thought my android was 4.2 while actually it's 4.4 and 19 would have worked. Or maybe 19 would have worked on android 4.2. Or maybe changing renderscriptTargetApi was unnecessary. Or something

Anyway, that's a solution right there. William, do you have any input on what THE solution should be?

**Comment by ars3niy** [comment]
Looks like release version of the auto-generated ScriptC_yuvToRgb.java doesn't depend on the target API level, only debug version does. It all comes down to the fact that the distributed package appears to be a debug build. So the other (and probably the only other) option would be to distribute release build instead.
