### ISSUE TITLE
crash 001

### ISSUE THREAD

**Issue by zoff99** [Antox/Antox#383]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'scala.collection.mutable.ArrayBuffer chat.tox.antox.data.AntoxDB.getMessageList(scala.Option, int)' on a null object reference
	at chat.tox.antox.activities.GenericChatActivity.getActiveMessageList(GenericChatActivity.scala:277)
	at chat.tox.antox.activities.GenericChatActivity.onCreate(GenericChatActivity.scala:92)
	at chat.tox.antox.activities.ChatActivity.onCreate(ChatActivity.scala:46)
	at android.app.Activity.performCreate(Activity.java:6876)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)

**Comment by zoff99** [comment]
i am getting these often

**Comment by zoff99** [comment]
should be fixed in latest 0.25.x
