### ISSUE TITLE
Cannot import profile

### ISSUE THREAD

**Issue by raspbeguy** [Antox/Antox#418]
Hello,
I am unable to import any profile in Antox, from toxic nor qTox. Whenever I try, Antox displays a yellow crash screen. I didn't see any solving element in #284 that could apply to my case.

Here is the crash log it produced:
```
Errormesage:
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/chat.tox.antox-1/base.apk"],nativeLibraryDirectories=[/data/app/chat.tox.antox-1/lib/arm, /system/fake-libs, /data/app/chat.tox.antox-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libtox4j-c.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
	at java.lang.System.loadLibrary(System.java:1530)
	at im.tox.tox4j.impl.jni.ToxLoadJniLibrary$.load(ToxLoadJniLibrary.scala:50)
	at im.tox.tox4j.impl.jni.ToxLoadJniLibrary.load(ToxLoadJniLibrary.scala)
	at im.tox.tox4j.impl.jni.ToxCryptoJni.<clinit>(ToxCryptoJni.java:7)
	at im.tox.tox4j.impl.jni.ToxCryptoJni.toxIsDataEncrypted(Native Method)
	at im.tox.tox4j.impl.jni.ToxCryptoImpl$.isDataEncrypted(ToxCryptoImpl.scala:26)
	at chat.tox.antox.tox.ToxDataFile$.isEncrypted(ToxDataFile.scala:15)
	at chat.tox.antox.tox.ToxDataFile$.isEncrypted(ToxDataFile.scala:37)
	at chat.tox.antox.tox.ToxDataFile.isEncrypted(ToxDataFile.scala:48)
	at chat.tox.antox.activities.CreateAccountActivity.onImportFileSelected(CreateAccountActivity.scala:398)
	at chat.tox.antox.activities.CreateAccountActivity$$anon$5.onSelectedFilePaths(CreateAccountActivity.scala:366)
	at com.github.angads25.filepicker.view.FilePickerDialog$1.onClick(FilePickerDialog.java:103)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22429)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6169)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)


===================================

--------- beginning of system
02-06 00:40:37.637 27954 27954 W ViewRootImpl[ProfilesUI]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x28, repeatCount=0, eventTime=369652278, downTime=369652264, deviceId=-1, source=0x101 }
02-06 00:40:37.637 27954 27954 W ViewRootImpl[ProfilesUI]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x28, repeatCount=0, eventTime=369652278, downTime=369652264, deviceId=-1, source=0x101 }
02-06 00:40:37.637 27954 27954 W ViewRootImpl[ProfilesUI]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x28, repeatCount=0, eventTime=369652278, downTime=369652264, deviceId=-1, source=0x101 }
02-06 00:40:37.716 27954 27954 W ViewRootImpl[ProfilesUI]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x28, repeatCount=0, eventTime=369652278, downTime=369652264, deviceId=-1, source=0x101 }
02-06 00:40:37.716 27954 27954 W ViewRootImpl[ProfilesUI]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x28, repeatCount=0, eventTime=369652278, downTime=369652264, deviceId=-1, source=0x101 }
02-06 00:40:37.716 27954 27954 W ViewRootImpl[ProfilesUI]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x28, repeatCount=0, eventTime=369652278, downTime=369652264, deviceId=-1, source=0x101 }
02-06 00:40:37.716 27954 27954 W ViewRootImpl[ProfilesUI]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x28, repeatCount=0, eventTime=369652278, downTime=369652264, deviceId=-1, source=0x101 }
02-06 00:40:37.716 27954 27954 W ViewRootImpl[ProfilesUI]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x28, repeatCount=0, eventTime=369652278, downTime=369652264, deviceId=-1, source=0x101 }
02-06 00:40:37.716 27954 27954 W ViewRootImpl[ProfilesUI]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x28, repeatCount=0, eventTime=369652278, downTime=369652264, deviceId=-1, source=0x101 }
--------- beginning of main
02-10 19:09:45.462 30522 30533 W art     : Suspending all threads took: 6.806ms
02-10 19:09:45.465 30522 30533 I art     : Background partial concurrent mark sweep GC freed 1580(84KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 17MB/28MB, paused 7.581ms total 58.302ms
02-10 19:09:45.488 30522 30522 I System.out: MainApplication:LoginActivity:onCreate
02-10 19:09:52.445 30522 30522 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
02-10 19:09:52.445 30522 30522 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
02-10 19:09:52.445 30522 30522 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
02-10 19:09:52.461 30522 30522 D AndroidRuntime: Shutting down VM
02-10 19:09:52.479 30522 30522 I System.out: MainApplication:288:stack trace ok
02-10 19:09:52.534 30522 30522 I System.out: MainApplication:288:crash file=/storage/emulated/0/Antox/crash_2017-02-10_19_09_52.txt
02-10 19:09:52.537 30522 30522 I System.out: MainApplication:288:crashes[set]=3
02-10 19:09:52.537 30522 30522 I System.out: MainApplication:288:?:60000 < 1486750192537
02-10 19:09:52.537 30522 30522 I System.out: MainApplication:288:?:1486750132537
02-10 19:09:52.537 30522 30522 I System.out: Shutdown:001
02-10 19:09:52.537 30522 30522 I System.out: Shutdown:002
02-10 19:09:52.537 30522 30522 I System.out: Shutdown:003
02-10 19:09:52.538 30522 30522 I System.out: Shutdown:004
02-10 19:09:52.538 30522 30522 W System.err: chat.tox.antox.data.UserDB$NotLoggedInException
02-10 19:09:52.538 30522 30522 W System.err: 	at chat.tox.antox.data.UserDB$$anonfun$getActiveUser$1.apply(UserDB.scala:98)
02-10 19:09:52.538 30522 30522 W System.err: 	at chat.tox.antox.data.UserDB$$anonfun$getActiveUser$1.apply(UserDB.scala:98)
02-10 19:09:52.538 30522 30522 W System.err: 	at scala.Option.getOrElse(Option.scala:121)
02-10 19:09:52.538 30522 30522 W System.err: 	at chat.tox.antox.data.UserDB.getActiveUser(UserDB.scala:98)
02-10 19:09:52.538 30522 30522 W System.err: 	at chat.tox.antox.data.UserDB.getActiveUserDetails(UserDB.scala:217)
02-10 19:09:52.538 30522 30522 W System.err: 	at chat.tox.antox.data.State$.shutdown(State.scala:154)
02-10 19:09:52.538 30522 30522 W System.err: 	at chat.tox.antox.data.State.shutdown(State.scala)
02-10 19:09:52.538 30522 30522 W System.err: 	at chat.tox.antox.MainApplication.handleUncaughtException(MainApplication.java:227)
02-10 19:09:52.538 30522 30522 W System.err: 	at chat.tox.antox.MainApplication.access$000(MainApplication.java:34)
02-10 19:09:52.539 30522 30522 W System.err: 	at chat.tox.antox.MainApplication$1.uncaughtException(MainApplication.java:71)
02-10 19:09:52.539 30522 30522 W System.err: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-10 19:09:52.539 30522 30522 W System.err: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
02-10 19:09:52.539 30522 30522 I System.out: MainApplication:288:componentInfo=ComponentInfo{chat.tox.antox/chat.tox.antox.activities.CreateAccountActivity} class=chat.tox.antox.activities.CreateAccountActivity
02-10 19:09:52.542 30522 30522 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void chat.tox.antox.tox.ToxService.onDestroy()' on a null object reference
02-10 19:09:52.543 30522 30522 W System.err: 	at chat.tox.antox.MainApplication.handleUncaughtException(MainApplication.java:242)
02-10 19:09:52.543 30522 30522 W System.err: 	at chat.tox.antox.MainApplication.access$000(MainApplication.java:34)
02-10 19:09:52.543 30522 30522 W System.err: 	at chat.tox.antox.MainApplication$1.uncaughtException(MainApplication.java:71)
02-10 19:09:52.543 30522 30522 W System.err: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-10 19:09:52.543 30522 30522 W System.err: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
02-10 19:09:52.543 30522 30522 I System.out: MainApplication:288:xx1 intent(1)=Intent { cmp=chat.tox.antox/.CrashActivity }
02-10 19:09:52.543 30522 30522 I System.out: MainApplication:288:xx1 intent(2)=Intent { flg=0x10008000 cmp=chat.tox.antox/.CrashActivity }
02-10 19:09:52.576 30522 30522 I System.out: MainApplication:288:xx2
02-10 19:09:52.576 30522 30522 I Process : Sending signal. PID: 30522 SIG: 9
02-10 19:09:52.728 10204 10204 I MultiDex: VM with version 2.1.0 has multidex support
02-10 19:09:52.728 10204 10204 I MultiDex: install
02-10 19:09:52.728 10204 10204 I MultiDex: VM has multidex support, MultiDex support library is disabled.
02-10 19:09:52.729 10204 10204 I System.out: MainApplication:837:onCreate
02-10 19:09:52.730 10204 10204 I System.out: MainApplication:837:crashes[load]=3
02-10 19:09:52.730 10204 10204 I System.out: MainApplication:837:last_crash_time[load]=0
02-10 19:09:52.731 10204 10204 I System.out: MainApplication:837:prevlast_crash_time[load]=0
02-10 19:09:52.744 10204 10204 I System.out: CrashActivity:onCreate
02-10 19:09:52.751 10204 10204 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-10 19:09:52.949 10204 10222 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
02-10 19:09:52.951 10204 10222 I OpenGLRenderer: Initialized EGL, version 1.4
02-10 19:09:52.951 10204 10222 D OpenGLRenderer: Swap behavior 1
02-10 19:30:07.453 10204 10204 I System.out: MainApplication:LoginActivity:onCreate
02-10 19:30:20.004 10204 10204 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
02-10 19:30:20.004 10204 10204 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
02-10 19:30:20.004 10204 10204 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
02-10 19:30:20.010 10204 10204 D AndroidRuntime: Shutting down VM
02-10 19:30:20.021 10204 10204 I System.out: MainApplication:837:stack trace ok
```
Thank you in advance.

**Comment by zoff99** [comment]
```
couldn't find "libtox4j-c.so"
```

you need to upgrade to the latest Antox version.

**Comment by raspbeguy** [comment]
I am already unig the last version (from the official tox repo on fdroid).

**Comment by wiiaam** [comment]
@raspbeguy This was fixed pretty recently, the latest apk on fdroid should be working

**Comment by raspbeguy** [comment]
Yeah, sorry for late response, it works now.
