### ISSUE TITLE
Antox crash when try to take picture in chatActivity

### ISSUE THREAD

**Issue by askymore** [Antox/Antox#506]
Android version:7.1

Crash info:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: chat.tox.antox, PID: 20271
    android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/Antoxpic%200754%201612702648.jpg exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1796)
        at android.net.Uri.checkFileUriExposed(Uri.java:2354)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:845)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:8961)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:8946)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
        at android.app.Activity.startActivityForResult(Activity.java:4398)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
        at android.app.Activity.startActivityForResult(Activity.java:4356)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
        at chat.tox.antox.activities.ChatActivity$$anon$3.onClick(ChatActivity.scala:124)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22465)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6395)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by tigerzhang** [comment]
Uri like file:// cannot be sent via Intent in Android version 7 anymore.

**Comment by TheJackiMonster** [comment]
My Android does not crash but the application seems to disconnect and all chats etc. hide from menus.

**Comment by zoff99** [comment]
@tigerzhang @TheJackiMonster Antox is no longer in active maintainance.
please use https://f-droid.org/packages/com.zoffcc.applications.trifa/
which is the currently maintained android tox client
